#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'i3pystatus==3.34','console_scripts','i3pystatus'
__requires__ = 'i3pystatus==3.34'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('i3pystatus==3.34', 'console_scripts', 'i3pystatus')()
    )
